name: quimios-etl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - selenium
  - pandas
  - python-dotenv
  - psycopg2
  - sqlalchemy
  - requests
  - pip
  - pip:
    - webdriver-manager
